// import { Geist, Geist_Mono } from "next/font/google";
import { Roboto } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/shared/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Next Js App",
  description: "Generated by My Next Js App",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={roboto.className}>
        <div className="bg-slate-500">{/* <Navbar /> */}</div>
        {children}
        <div className="bg-slate-500 items-center text-center">
          <footer>Footer</footer>
        </div>
      </body>
    </html>
  );
}
